name: 'HTML to PDF'
description: 'Node module that converts HTML files to PDFs.'
author: 'fifsky@gmail.com'
inputs:
  htmlFile:
    description: 'html path'
    required: true

  output:
    description: 'output file path'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: "blue"
  icon: "file"