name: Test Build Pdf

on: [push, pull_request]

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./example.html
          outputFile: ./example.pdf
          pdfOptions: '{"margin": {"top": "1000", "left": "100", "right": "100", "bottom": "100"}}'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Example PDF
          path: ./example.pdf